### ISSUE TITLE
Loadshedding Suspension

### ISSUE THREAD

**Issue by KosieKramer** [tinuva/ha-coct-loadshedding#1]
## Version of the custom_component
v1.0.3

## Describe the bug
Great and very useful component!

Question about loadshedding suspension: This morning (15/7/22) between midnight and 6:04, the coct_loadshedding_stage sensor became unavailable. Does this translate to suspension of loadshedding?

Thanks!

**Comment by tinuva** [comment]
I noticed the same thing and I believe there is a bug in the code testing if I received a valid result from the CoCT endpoint. Unfortunately I noticed it after the fact, so I have made some changes that I want to test when it happens again and will then push an update.

**Comment by tinuva** [comment]
Published version 1.0.4 which should fix the issue according to my simulation of the endpoint.

**Comment by KosieKramer** [comment]
Will install and keep an eye out.

**Comment by tinuva** [comment]
Closing. Looks like 1.0.4 resolved the issue on my own HA.
