### ISSUE TITLE
COCT state must be dependent on Eskom state

### ISSUE THREAD

**Issue by tiaanv** [tinuva/ha-coct-loadshedding#3]
Currently, the COCT stage will update as soon as COCT publish their reduced stage (at least that's how it seems). 

Most of the time this updates the COCT stage before the actual loadshedding is active (based on Eskom Stage).

To resolve this I propose the COCT stage should only change to a non-zero value when the Eskom stage changes to a non-zero value.

at least for the sensor value...  Perhaps the attributes could still represent the independent announced stage?

The alternative to me is to simply create my own template sensor that does the above logic, but I thought I'd give you some initial feedback.

**Comment by tinuva** [comment]
Hmm, there is a new `startTime` introduced on the endpoint. Will use that right now.

**Comment by tinuva** [comment]
Try version 1.0.7

**Comment by tiaanv** [comment]
working as expected now.
